#!/usr/bin/env bash
# /opt/data/scripts/hermes-init.sh
# Container init — starts the Hermes gateway and WebUI daemon.
# Lives on the persistent /opt/data volume so it survives container rebuilds.
#
# Used as docker-compose `command:`:
#   command: /opt/data/scripts/hermes-init.sh
#
# The container's main-wrapper.sh (entrypoint) activates the agent venv,
# sets HOME=/opt/data, and drops privileges to the hermes user before
# exec-ing this script. We inherit all of that.

set -euo pipefail

GATEWAY_READY_TIMEOUT=${GATEWAY_READY_TIMEOUT:-30}
WEBUI_DIR="${WEBUI_DIR:-/opt/data/hermes-webui}"
WEBUI_REPO="${WEBUI_REPO:-https://github.com/nesquena/hermes-webui.git}"
HERMES_HOME="${HERMES_HOME:-/opt/data}"

log() { printf '[hermes-init] %s\n' "$*"; }

# ── Gateway ────────────────────────────────────────────────────────
log "Starting gateway…"
hermes gateway run &
GATEWAY_PID=$!

# Forward signals to the gateway so the container shuts down cleanly.
cleanup() {
    log "Caught signal — stopping gateway (PID $GATEWAY_PID)"
    kill -TERM "$GATEWAY_PID" 2>/dev/null || true
    wait "$GATEWAY_PID" 2>/dev/null || true
    exit 0
}
trap cleanup TERM INT QUIT

# Wait for gateway health.
log "Waiting for gateway health…"
_start=$(date +%s)
while true; do
    if curl -sf http://localhost:9119/api/status >/dev/null 2>&1; then
        log "Gateway healthy after $(( $(date +%s) - _start ))s"
        break
    fi
    if ! kill -0 "$GATEWAY_PID" 2>/dev/null; then
        log "ERROR: gateway exited prematurely"
        wait "$GATEWAY_PID" 2>/dev/null || true
        exit 1
    fi
    if [ $(( $(date +%s) - _start )) -ge "$GATEWAY_READY_TIMEOUT" ]; then
        log "ERROR: gateway did not become healthy within ${GATEWAY_READY_TIMEOUT}s"
        exit 1
    fi
    sleep 1
done

# ── WebUI ──────────────────────────────────────────────────────────
_start_webui() {
    cd "$WEBUI_DIR"
    export HERMES_HOME
    if ./ctl.sh start 2>&1; then
        log "WebUI started — http://<host>:8787"
    else
        log "WARNING: WebUI failed to start — check /opt/data/webui.log"
    fi
    cd "$HERMES_HOME"
}

if [ "${HERMES_WEBUI_ENABLED:-1}" != "1" ]; then
    log "WebUI disabled (HERMES_WEBUI_ENABLED != 1)"
elif [ -d "$WEBUI_DIR" ]; then
    log "WebUI found at $WEBUI_DIR — starting…"
    _start_webui
elif [ -n "${HERMES_WEBUI_PASSWORD:-}" ]; then
    # ── First boot: auto-clone and configure ──────────────────────
    log "WebUI not installed — auto-cloning (HERMES_WEBUI_PASSWORD is set)…"
    if command -v git >/dev/null 2>&1; then
        if git clone --depth 1 "$WEBUI_REPO" "$WEBUI_DIR" 2>&1; then
            log "Cloned $WEBUI_REPO → $WEBUI_DIR"
        else
            log "WARNING: git clone failed — check network; WebUI won't start"
            log "Clone manually: git clone $WEBUI_REPO $WEBUI_DIR"
        fi
    else
        log "WARNING: git not found — cannot auto-clone WebUI"
    fi

    if [ -d "$WEBUI_DIR" ]; then
        # Create .env from example if it doesn't exist.
        if [ ! -f "$WEBUI_DIR/.env" ]; then
            if [ -f "$WEBUI_DIR/.env.example" ]; then
                cp "$WEBUI_DIR/.env.example" "$WEBUI_DIR/.env"
                # Write the minimal config needed for in-container use.
                cat >> "$WEBUI_DIR/.env" <<EOF

# ── Auto-generated by hermes-init.sh ──────────────────────────────
HERMES_WEBUI_AGENT_DIR=/opt/hermes
HERMES_WEBUI_PYTHON=/opt/hermes/.venv/bin/python3
HERMES_WEBUI_HOST=${HERMES_WEBUI_HOST:-0.0.0.0}
HERMES_WEBUI_PORT=${HERMES_WEBUI_PORT:-8787}
HERMES_WEBUI_PASSWORD=${HERMES_WEBUI_PASSWORD}
HERMES_WEBUI_STATE_DIR=/opt/data/hermes-webui-state
HERMES_WEBUI_DEFAULT_WORKSPACE=/opt/data/workspace
HERMES_CONFIG_PATH=/opt/data/config.yaml
HERMES_WEBUI_SKIP_ONBOARDING=1
EOF
                log "Created $WEBUI_DIR/.env with auth + agent paths"
            fi
        fi
        _start_webui
    fi
else
    log "WebUI not installed and HERMES_WEBUI_PASSWORD not set — skipping"
    log "To enable: set HERMES_WEBUI_PASSWORD in your docker-compose .env and restart"
fi

# ── Wait ───────────────────────────────────────────────────────────
log "Gateway running (PID $GATEWAY_PID) — waiting…"
wait "$GATEWAY_PID"